name: Android CI Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v3
    - name: set up java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: setup gradle
      uses: gradle/gradle-build-action@v2
    - name: build
      run: ./gradlew build --no-daemon

  integration-test:
    # disable since it is not working
    if: ${{ false }}
    runs-on: macos-latest
    steps:
    - name: checkout project
      uses: actions/checkout@v3

    - name: set up java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        script: ./gradlew connectedCheck --no-daemon